apply plugin: 'org.springframework.boot'

dependencies {
    // Módulos del proyecto
    implementation project(':reactive-web')
    implementation project(':model')
    implementation project(':usecase')

    // Spring Boot base + Actuator + Devtools
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    runtimeOnly 'org.springframework.boot:spring-boot-devtools'

    // OpenAPI/Swagger para WebFlux (UI en /swagger-ui.html)
    implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.6.0'

    // Lombok (por si este módulo lo usa)
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    // Tests
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.projectreactor:reactor-test'
    testImplementation 'com.tngtech.archunit:archunit:1.4.1'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind'

    // Testcontainers (BOM para alinear versiones)
    testImplementation platform('org.testcontainers:testcontainers-bom:1.20.1')
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:mysql'
    testImplementation 'org.testcontainers:localstack'
}

tasks.register('explodedJar', Copy) {
    with jar
    into layout.buildDirectory.dir("exploded")
}

jar { enabled = false } // desactiva *-plain.jar

bootJar {
    archiveFileName = "${project.getParent().getName()}.${archiveExtension.get()}"
}

tasks.withType(Test).configureEach { useJUnitPlatform() }
